import os, json, urllib.request, urllib.error, logging
from pathlib import Path

logger = logging.getLogger(__name__)

GITHUB_TOKEN = os.getenv("GITHUB_BACKUP_TOKEN", "")
GIST_ID      = os.getenv("GITHUB_GIST_ID", "")
API_BASE     = "https://api.github.com"

def _headers():
    return {
            "Authorization": f"token {GITHUB_TOKEN}",
                    "Content-Type": "application/json",
                            "Accept": "application/vnd.github.v3+json",
                                    "User-Agent": "SourceFinder-Backup/1.0",
                                        }

                                        def _req(method, url, data=None):
                                            body = json.dumps(data).encode() if data else None
                                                req  = urllib.request.Request(url, data=body, headers=_headers(), method=method)
                                                    try:
                                                            with urllib.request.urlopen(req, timeout=10) as r:
                                                                        return json.loads(r.read())
                                                                            except urllib.error.HTTPError as e:
                                                                                    body = e.read()
                                                                                            logger.warning("GitHub backup HTTP error %s: %s", e.code, body[:300])
                                                                                                    return None
                                                                                                        except Exception as e:
                                                                                                                logger.warning("GitHub backup error: %s", e)
                                                                                                                        return None
                                                                                                                        
                                                                                                                        def push_backup(filename, content_dict):
                                                                                                                            if not GITHUB_TOKEN:
                                                                                                                                    logger.warning("GITHUB_BACKUP_TOKEN not set — skipping backup")
                                                                                                                                            return
                                                                                                                                                if not GIST_ID:
                                                                                                                                                        logger.warning("GITHUB_GIST_ID not set — skipping backup")
                                                                                                                                                                return
                                                                                                                                                                    files = {filename: {"content": json.dumps(content_dict, indent=2)}}
                                                                                                                                                                        result = _req("PATCH", f"{API_BASE}/gists/{GIST_ID}", {"files": files})
                                                                                                                                                                            if result:
                                                                                                                                                                                    logger.info("Backup pushed: %s", filename)
                                                                                                                                                                                        else:
                                                                                                                                                                                                logger.warning("Backup push failed for %s", filename)
                                                                                                                                                                                                
                                                                                                                                                                                                def pull_backup(filename):
                                                                                                                                                                                                    if not GITHUB_TOKEN or not GIST_ID:
                                                                                                                                                                                                            return None
                                                                                                                                                                                                                result = _req("GET", f"{API_BASE}/gists/{GIST_ID}")
                                                                                                                                                                                                                    if not result:
                                                                                                                                                                                                                            return None
                                                                                                                                                                                                                                files = result.get("files", {})
                                                                                                                                                                                                                                    if filename not in files:
                                                                                                                                                                                                                                            return None
                                                                                                                                                                                                                                                raw_url = files[filename].get("raw_url")
                                                                                                                                                                                                                                                    if not raw_url:
                                                                                                                                                                                                                                                            content = files[filename].get("content")
                                                                                                                                                                                                                                                                    return json.loads(content) if content else None
                                                                                                                                                                                                                                                                        try:
                                                                                                                                                                                                                                                                                req = urllib.request.Request(raw_url, headers={"User-Agent": "SourceFinder/1.0"})
                                                                                                                                                                                                                                                                                        with urllib.request.urlopen(req, timeout=10) as r:
                                                                                                                                                                                                                                                                                                    return json.loads(r.read())
                                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                                logger.warning("Failed to fetch gist raw content: %s", e)
                                                                                                                                                                                                                                                                                                                        return None
                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                        def restore_if_empty(local_path, gist_filename, default):
                                                                                                                                                                                                                                                                                                                            needs_restore = False
                                                                                                                                                                                                                                                                                                                                if not local_path.exists():
                                                                                                                                                                                                                                                                                                                                        needs_restore = True
                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                    try:
                                                                                                                                                                                                                                                                                                                                                                current = json.loads(local_path.read_text())
                                                                                                                                                                                                                                                                                                                                                                            if current == default:
                                                                                                                                                                                                                                                                                                                                                                                            needs_restore = True
                                                                                                                                                                                                                                                                                                                                                                                                    except:
                                                                                                                                                                                                                                                                                                                                                                                                                needs_restore = True
                                                                                                                                                                                                                                                                                                                                                                                                                    if needs_restore and GITHUB_TOKEN and GIST_ID:
                                                                                                                                                                                                                                                                                                                                                                                                                            logger.info("Local data empty — restoring %s from Gist...", gist_filename)
                                                                                                                                                                                                                                                                                                                                                                                                                                    data = pull_backup(gist_filename)
                                                                                                                                                                                                                                                                                                                                                                                                                                            if data:
                                                                                                                                                                                                                                                                                                                                                                                                                                                        local_path.parent.mkdir(exist_ok=True, parents=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    local_path.write_text(json.dumps(data, indent=2))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                logger.info("Restored %s from Gist backup", gist_filename)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                logger.warning("Could not restore %s from Gist", gist_filename)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return False
